name: Susan Perkins
title: Susan H Perkins, BSEng | Resume
email: perkins.susan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the resume and blog for Susan H Perkins, Senior Software Developer.  This is my
  jekyll-theme-based resume hosted on Github Pages.
#baseurl: '/resume' # the subpath of your site, e.g. /blog
url: "http://shperkins.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SusanThePerkins
github_username:  perkinss

# Build settings
theme: jekyll-theme-tao
